### ISSUE TITLE
Bandwidth `h` depends on `prob`

### ISSUE THREAD

**Issue by lindeloev** [robjhyndman/hdrcde#10]
Here is some tri-modal data:
```r
x = c(rnorm(500, 30, 3), rnorm(200, 50, 1.5), 60 + rexp(200, 0.1))
```

And here are some regions:
```r
hdrcde::hdr.den(x, prob = c(50, 75, 95))
```
![image](https://user-images.githubusercontent.com/1439417/99795387-00fbf600-2b2c-11eb-98dc-7050a1fb9741.png)

If you just use a single `prob`, the Bandwidth (`h`?) is much broader and hence the results differ from the above:
```
hdrcde::hdr.den(x, prob = 95)
```
![image](https://user-images.githubusercontent.com/1439417/99795569-43bdce00-2b2c-11eb-9564-3aa017dfa3d3.png)

This non-replicability surprised me since I expected the bandwidth to be independent of `prob`.

**Comment by robjhyndman** [comment]
As noted in the help files, the default bandwidth is that proposed by Samworth and Wand (Annals of Statistics, 2010) which is tailored to the particular HDR requested. So it will change depending on the value of the prob argument. If you don't want to use this bandwidth, then specify the h argument as well.

**Comment by lindeloev** [comment]
Thanks for the clarification. I ended up using h = 'SJ' which is better for
the densities I work with. Feel free to close this issue now.
