### ISSUE TITLE
hdr function sometimes switches start and end 

### ISSUE THREAD

**Issue by alpersr** [robjhyndman/hdrcde#12]
Hi, 
we are using the hdr function for determining the high density regions in a simulation where we test many model parameter combinations. For a few parameters, the start and end of the intervals seem to be switched. Which parameters are effected depends on the seed and the nn we choose, so changing them helps in one case but starts the issue in another case.

Below you can find code to reproduce the issue. We use version 3.4 from CRAN.

```
param1 <- 12.444444
param2 <- 2.414141
alpha <- (param1/param2)^2
beta <- param1/param2^2
y <- do.call(dgamma, c(list(seq(0, 24 - (1 / 24), by = 1 / 24)), alpha, beta))

set.seed(123)
hdr_df1 <- hdrcde::hdr(den = data.frame(x = 1:576, y = y), prob = 80)$hdr
#           [,1]          [,2]
# 80%  369 220.5709

set.seed(1234)
hdr_df2 <- hdrcde::hdr(den = data.frame(x = 1:576, y = y), prob = 80)$hdr
#                  [,1]   [,2]
# 80% 221.2811  368

```

--- UPDATE ---
I just changed the example code above so you don't need an additional dataframe. 
Further investigating our results we found two more bugs sometimes happening together with the first one:

Sometimes hdr()$hdr ends up with three entries, as it includes the start of the dataframe as the first entry:
```
param1 <- 9.313131
param2 <- 3.989898
alpha <- (param1/param2)^2
beta <- param1/param2^2
y <- do.call(dgamma, c(list(seq(0, 24 - (1 / 24), by = 1 / 24)), alpha, beta))

set.seed(123)
hdrcde::hdr(den = data.frame(x = 1:576, y = y), prob = 80)$hdr
#          [,1]   [,2]        [,3]
# 80%    1  323 91.61582
# Warning message:
# In hdr.ends(den, falpha$falpha[i]) : Some HDRs are incomplete

set.seed(1234)
hdrcde::hdr(den = data.frame(x = 1:576, y = y), prob = 80)$hdr
#                   [,1]   [,2]
# 80% 93.34355  319
```

And sometimes it also includes the last entry of the dataframe, so there are four entries in total:
```
param1 <- 9.111111
param2 <- 4.757576
alpha <- (param1/param2)^2
beta <- param1/param2^2
y <- do.call(dgamma, c(list(seq(0, 24 - (1 / 24), by = 1 / 24)), alpha, beta))

set.seed(123)
hdrcde::hdr(den = data.frame(x = 1:576, y = y), prob = 80)$hdr
#         [,1]   [,2]           [,3]   [,4]
# 80%    1  323 64.30771  576

set.seed(1234)
hdrcde::hdr(den = data.frame(x = 1:576, y = y), prob = 80)$hdr
#                   [,1]   [,2]
# 80% 65.66193  319
```

**Comment by robjhyndman** [comment]
Thanks. Fixed in https://github.com/robjhyndman/hdrcde/commit/1338622c3a57bf46c215870e04a55af8b5c78755
