### ISSUE TITLE
hdr.den() failure on some data sets

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/hdrcde#8]
@mitchelloharawild. Can you please post the example giving problems.

**Comment by mitchelloharawild** [comment]
Which failure do you mean?
If the density plot from today, it was a difference in the density's bandwidth.

**Comment by robjhyndman** [comment]
Do you remember the details? i.e., arguments which gave problems?

**Comment by mitchelloharawild** [comment]
I think the manual plot of the density had a different bandwidth from what is used in the package, so there is no issue. I'll ask the group tomorrow.
