### ISSUE TITLE
[Feature request] - Add option to suppress plotting

### ISSUE THREAD

**Issue by fentonscode** [robjhyndman/hdrcde#9]
**Description**

I am using hdr.den to compute the HDR as an interval over thousands of distributions and would like to suppress the automatic plotting without having to resort to workarounds. Adding a flag to prevent output would be extremely handy to stop spamming the plotting engine with additional graphics.

**System information**
 - R version: 4.0.2
 - OS: Windows 10 64 bit

**Comment by robjhyndman** [comment]
Why can't you use the hdr function for that?

**Comment by fentonscode** [comment]
@robjhyndman I was unaware `hdr` did not plot! Thanks for the hint. According to page 6 of the document [here](https://cran.r-project.org/web/packages/hdrcde/hdrcde.pdf) it appears all three functions will calculate **and** plot, hence my usage of `hdr.den`

**Comment by robjhyndman** [comment]
Good point. I've now split the help files so there is one for each function.
